on:
  push:
  schedule:
    - cron: '0,10,20,30,40,50 * * * *'
  pull_request:
    types: [labeled]
  pull_request_target:
    types: [labeled, synchronize]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo context object
        run: echo $GITHUB_OBJ
        env:
          GITHUB_OBJ: ${{ toJSON(github) }}
      - name: Run run.sh
        run: ./run.sh