on:
  schedule:
    - cron: '0,10,20,30,40,50 * * * *'
  pull_request:
    types: [labeled]
  pull_request_target:
    types: [labeled, synchronize]
steps:
  - name: Echo context object
    run: echo ${{ toJson(github) }}
  - name: Run run.sh
    run: ./run.sh