on:
  push:
  schedule:
    - cron: '0,10,20,30,40,50 * * * *'
  pull_request:
    types: [labeled]
  pull_request_target:
    types: [labeled, synchronize]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo context object
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT
      - name: Some context detection
        run: echo $PWD; ls -al; ls -al ../; ls -al ../../
      - name: Run run.sh
        run: ../run.sh